/** @type {import('tailwindcss').Config} */
module.exports = {
  // Scan all Templ templates and Go handler files for class usage
  content: [
    './internal/views/**/*.templ',
    './internal/**/*.go',
    './cmd/**/*.go',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Material You / DevArtisan colour tokens ──────────────────────────
        'surface-bright':                '#3a393a',
        'surface-container-highest':     '#353436',
        'on-primary-container':          '#005170',
        'on-primary':                    '#00344a',
        'background':                    '#131314',
        'secondary-fixed':               '#dce3f2',
        'surface-container-low':         '#1c1b1c',
        'on-tertiary-container':         '#7d371d',
        'tertiary-container':            '#ffa688',
        'primary-fixed-dim':             '#7dd0ff',
        'inverse-on-surface':            '#313031',
        'on-secondary-fixed-variant':    '#404753',
        'on-primary-fixed':              '#001e2c',
        'primary-fixed':                 '#c4e7ff',
        'surface-container-high':        '#2a2a2b',
        'tertiary':                      '#ffcdbd',
        'surface-container':             '#201f20',
        'outline-variant':               '#3e484f',
        'inverse-primary':               '#00658b',
        'surface':                       '#131314',
        'primary-container':             '#58c7ff',
        'on-tertiary-fixed-variant':     '#763219',
        'tertiary-fixed':                '#ffdbd0',
        'on-secondary-fixed':            '#151c26',
        'on-background':                 '#e5e2e3',
        'on-error':                      '#690005',
        'on-surface-variant':            '#bec8d0',
        'on-secondary':                  '#2a313c',
        'surface-tint':                  '#7dd0ff',
        'secondary-fixed-dim':           '#c0c7d5',
        'tertiary-fixed-dim':            '#ffb59c',
        'surface-container-lowest':      '#0e0e0f',
        'on-secondary-container':        '#aeb5c4',
        'on-tertiary-fixed':             '#390c00',
        'on-error-container':            '#ffdad6',
        'secondary':                     '#c0c7d5',
        'surface-dim':                   '#131314',
        'on-tertiary':                   '#591c05',
        'on-surface':                    '#e5e2e3',
        'inverse-surface':               '#e5e2e3',
        'error-container':               '#93000a',
        'outline':                       '#88929a',
        'secondary-container':           '#404753',
        'primary':                       '#abdeff',
        'on-primary-fixed-variant':      '#004c69',
        'surface-variant':               '#353436',
        'error':                         '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        serif:    ['Playfair Display', 'serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
