package services

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/sethum-VS/my-portfolio/internal/models"
	"github.com/sethum-VS/my-portfolio/internal/utils"
	"google.golang.org/genai"
)

// ParseReadmeToProductContext takes a raw README markdown string and uses Gemini to extract
// structured project information into a models.Product struct.
func ParseReadmeToProductContext(ctx context.Context, readme string) (*models.Product, error) {
	// Initialize the Google GenAI client
	client, err := genai.NewClient(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create genai client: %w", err)
	}

	model := "gemini-2.5-flash"

	// Define the master system instruction for the AI
	systemInstructionText := "You are an expert Technical Writer and Data Extractor. Your job is to analyze the provided raw README.md file and extract its contents into a strict JSON object. Follow these exact rules for each field:\n\n" +
		"Project ID: Extract a marketing-friendly display name that sounds cool but remains aligned with the technical name.\n\n" +
		"Project Title: Extract the straightforward technical name or the repository name.\n\n" +
		"Subtitle: Write a punchy, compelling one-liner description.\n\n" +
		"Challenge: Describe the core problem or challenge the project aims to solve. Limit to one concise paragraph.\n\n" +
		"Solution: Explain the approach to solving the challenge. Limit to one concise paragraph.\n\n" +
		"Architecture Overview: Provide high-level architecture details. Specifically, describe what is happening in the Mermaid.js script to explain the data flow.\n\n" +
		"Core Features: List the key features as a single comma-separated string.\n\n" +
		"Markdown architecture: Find the exact Mermaid.js script block that shows the project architecture. Return ONLY the raw Mermaid script without any surrounding text or backticks.\n\n" +
		"Technology Stack: Extract only the most impactful technology names (e.g., React, Node.js, PostgreSQL). Ignore minor libraries or versions. Return as a comma-separated string.\n\n" +
		"Display Stack: From the Technology Stack, select the top 3 or 4 absolute strongest, most highlighting technologies. Return as a comma-separated string (e.g., Go, React, Docker).\n\n" +
		"Hero Asset Path: Find the image or GIF link in the readme (typically ending in .gif or .webp) and return the raw URL."

	systemInstruction := &genai.Content{
		Parts: []*genai.Part{
			{
				Text: systemInstructionText,
			},
		},
	}

	// Configure the generation request for structured JSON output
	config := &genai.GenerateContentConfig{
		SystemInstruction: systemInstruction,
		ResponseMIMEType:  "application/json",
		ResponseSchema: &genai.Schema{
			Type: genai.TypeObject,
			Properties: map[string]*genai.Schema{
				"id":                    {Type: genai.TypeString, Description: "Project ID"},
				"title":                 {Type: genai.TypeString, Description: "Project Title"},
				"subtitle":              {Type: genai.TypeString},
				"challenge":             {Type: genai.TypeString},
				"solution":              {Type: genai.TypeString},
				"architecture_overview": {Type: genai.TypeString},
				"core_features":         {Type: genai.TypeString},
				"markdown_architecture": {Type: genai.TypeString},
				"technology_stack":      {Type: genai.TypeString},
				"display_stack":         {Type: genai.TypeString},
				"hero_asset_path":       {Type: genai.TypeString},
			},
			Required: []string{"id", "title", "subtitle", "challenge", "solution", "architecture_overview", "technology_stack", "display_stack"},
		},
	}

	// Prepare the prompt
	prompt := fmt.Sprintf("Extract project details from the following README content:\n\n%s", readme)

	// Call Gemini
	resp, err := client.Models.GenerateContent(ctx, model, genai.Text(prompt), config)
	if err != nil {
		return nil, fmt.Errorf("gemini generation failed: %w", err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no content generated by AI")
	}

	// Extract the JSON text from the response
	responseText := resp.Candidates[0].Content.Parts[0].Text

	// Define a temporary struct to hold the AI's specific flat JSON output
	type aiResponse struct {
		ID                   string `json:"id"`
		Title                string `json:"title"`
		Subtitle             string `json:"subtitle"`
		Challenge            string `json:"challenge"`
		Solution             string `json:"solution"`
		ArchitectureOverview string `json:"architecture_overview"`
		CoreFeatures         string `json:"core_features"`
		MarkdownArchitecture string `json:"markdown_architecture"`
		TechnologyStack      string `json:"technology_stack"`
		DisplayStack         string `json:"display_stack"`
		HeroAssetPath        string `json:"hero_asset_path"`
	}

	var raw aiResponse
	if err := json.Unmarshal([]byte(responseText), &raw); err != nil {
		return nil, fmt.Errorf("failed to unmarshal AI response: %w. Response text: %s", err, responseText)
	}

	// Map the AI response back to our models.Product struct, handling string-to-slice conversions
	product := &models.Product{
		ID:           raw.ID,
		Title:        raw.Title,
		Subtitle:     raw.Subtitle,
		Challenge:    raw.Challenge,
		Solution:     raw.Solution,
		Architecture: raw.ArchitectureOverview,
		ArchDiagram:  raw.MarkdownArchitecture,
		HeroGIF:      raw.HeroAssetPath,
		TechStack:    utils.SplitAndTrim(raw.TechnologyStack),
		DisplayStack: utils.SplitAndTrim(raw.DisplayStack),
		KeyFeatures:  utils.SplitAndTrim(raw.CoreFeatures),
	}

	return product, nil
}
