package services

import (
	"time"

	"github.com/sethum-VS/my-portfolio/internal/config"

	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sashabaranov/go-openai"
	"github.com/sethum-VS/my-portfolio/internal/models"
	"github.com/sethum-VS/my-portfolio/internal/utils"
)

// ParseReadmeToProductContext takes a raw README markdown string and uses NVIDIA NIM (GLM-5.2) to extract
// structured project information into a models.Product struct.
func ParseReadmeToProductContext(ctx context.Context, readme string) (*models.Product, error) {
	apiKey := config.AppConfig.NvidiaNIMAPI
	if apiKey == "" {
		return nil, fmt.Errorf("NVIDIA_NIM_API environment variable is not set")
	}

	cfg := openai.DefaultConfig(apiKey)
	baseURL := config.AppConfig.NvidiaNIMBaseURL
	if baseURL == "" {
		baseURL = "https://integrate.api.nvidia.com/v1"
	}
	cfg.BaseURL = baseURL
	client := openai.NewClientWithConfig(cfg)

	model := "z-ai/glm-5.2"

	// Define the master system instruction for the AI
	systemInstructionText := "You are an expert Technical Writer and Data Extractor. Your job is to analyze the provided raw README.md file and extract its contents into a strict JSON object. " +
		"Ensure your response is valid JSON and nothing else. Do not wrap the JSON in markdown code blocks. Follow these exact JSON keys for each field:\n\n" +
		"- \"id\": Extract a marketing-friendly display name that sounds cool but remains aligned with the technical name.\n" +
		"- \"title\": Extract the straightforward technical name or the repository name.\n" +
		"- \"subtitle\": Write a punchy, compelling one-liner description.\n" +
		"- \"challenge\": Describe the core problem or challenge the project aims to solve. Limit to one concise paragraph.\n" +
		"- \"solution\": Explain the approach to solving the challenge. Limit to one concise paragraph.\n" +
		"- \"architecture_overview\": Provide high-level architecture details. Specifically, describe what is happening in the Mermaid.js script to explain the data flow.\n" +
		"- \"core_features\": List the key features as a single comma-separated string.\n" +
		"- \"markdown_architecture\": Find the exact Mermaid.js script block that shows the project architecture. Return ONLY the raw Mermaid script without any surrounding text or backticks.\n" +
		"- \"technology_stack\": Extract only the most impactful technology names (e.g., React, Node.js, PostgreSQL). Ignore minor libraries or versions. Return as a comma-separated string.\n" +
		"- \"display_stack\": From the Technology Stack, select the top 3 or 4 absolute strongest, most highlighting technologies. Return as a comma-separated string (e.g., Go, React, Docker).\n" +
		"- \"hero_asset_path\": Find the image or GIF link in the readme (typically ending in .gif or .webp) and return the raw URL."

	prompt := fmt.Sprintf("Extract project details from the following README content:\n\n%s", readme)

	req := openai.ChatCompletionRequest{
		Model: model,
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    openai.ChatMessageRoleSystem,
				Content: systemInstructionText,
			},
			{
				Role:    openai.ChatMessageRoleUser,
				Content: prompt,
			},
		},
		Temperature: 1.0,
		TopP:        1.0,
		MaxTokens:   2000,
		ResponseFormat: &openai.ChatCompletionResponseFormat{
			Type: openai.ChatCompletionResponseFormatTypeJSONObject,
		},
	}

	primaryCtx, primaryCancel := context.WithTimeout(ctx, 12*time.Second)
	defer primaryCancel()

	resp, err := client.CreateChatCompletion(primaryCtx, req)
	if err != nil {
		shouldFailover := true

		// If it's an API error, only failover for certain status codes (like 401, 403, 429, 500+)
		if apiErr, ok := err.(*openai.APIError); ok {
			if apiErr.HTTPStatusCode == 400 {
				shouldFailover = false
			}
		}

		if shouldFailover {
			backupAPIKey := config.AppConfig.NvidiaAPIKeyBackup
			if backupAPIKey != "" {
				fmt.Printf("Primary NVIDIA API failed: %v. Falling back to backup key.\n", err)
				backupConfig := openai.DefaultConfig(backupAPIKey)
				backupConfig.BaseURL = baseURL
				backupClient := openai.NewClientWithConfig(backupConfig)

				backupCtx, backupCancel := context.WithTimeout(ctx, 12*time.Second)
				defer backupCancel()

				resp, err = backupClient.CreateChatCompletion(backupCtx, req)
				if err != nil {
					return nil, fmt.Errorf("nvidia nim generation failed with both primary and backup keys: %w", err)
				}
			} else {
				return nil, fmt.Errorf("nvidia nim generation failed: %w", err)
			}
		} else {
			return nil, fmt.Errorf("nvidia nim generation failed without failover: %w", err)
		}
	}

	if len(resp.Choices) == 0 {
		return nil, fmt.Errorf("no content generated by AI")
	}

	responseText := resp.Choices[0].Message.Content

	// Strip markdown blocks if the model accidentally wrapped the output
	responseText = strings.TrimSpace(responseText)
	if strings.HasPrefix(responseText, "```json") {
		responseText = strings.TrimPrefix(responseText, "```json")
		responseText = strings.TrimSuffix(responseText, "```")
	} else if strings.HasPrefix(responseText, "```") {
		responseText = strings.TrimPrefix(responseText, "```")
		responseText = strings.TrimSuffix(responseText, "```")
	}
	responseText = strings.TrimSpace(responseText)

	// Define a temporary struct to hold the AI's specific flat JSON output
	type aiResponse struct {
		ID                   string `json:"id"`
		Title                string `json:"title"`
		Subtitle             string `json:"subtitle"`
		Challenge            string `json:"challenge"`
		Solution             string `json:"solution"`
		ArchitectureOverview string `json:"architecture_overview"`
		CoreFeatures         string `json:"core_features"`
		MarkdownArchitecture string `json:"markdown_architecture"`
		TechnologyStack      string `json:"technology_stack"`
		DisplayStack         string `json:"display_stack"`
		HeroAssetPath        string `json:"hero_asset_path"`
	}

	var raw aiResponse
	if err := json.Unmarshal([]byte(responseText), &raw); err != nil {
		return nil, fmt.Errorf("failed to unmarshal AI response: %w. Response text: %s", err, responseText)
	}

	// Map the AI response back to our models.Product struct, handling string-to-slice conversions
	product := &models.Product{
		ID:           raw.ID,
		Title:        raw.Title,
		Subtitle:     raw.Subtitle,
		Challenge:    raw.Challenge,
		Solution:     raw.Solution,
		Architecture: raw.ArchitectureOverview,
		ArchDiagram:  raw.MarkdownArchitecture,
		HeroGIF:      raw.HeroAssetPath,
		TechStack:    utils.SplitAndTrim(raw.TechnologyStack),
		DisplayStack: utils.SplitAndTrim(raw.DisplayStack),
		KeyFeatures:  utils.SplitAndTrim(raw.CoreFeatures),
	}

	return product, nil
}
