package services

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/sethum-VS/my-portfolio/internal/models"
	"google.golang.org/genai"
)

// ParseReadmeToProductContext takes a raw README markdown string and uses Gemini to extract
// structured project information into a models.Product struct.
func ParseReadmeToProductContext(ctx context.Context, readme string) (*models.Product, error) {
	// Initialize the Google GenAI client
	// The client uses Application Default Credentials (ADC) by default.
	// Environment variables like GOOGLE_CLOUD_PROJECT are expected to be set.
	client, err := genai.NewClient(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create genai client: %w", err)
	}

	model := "gemini-2.5-flash"

	// Define the system instructions for the AI
	systemInstruction := &genai.Content{
		Parts: []*genai.Part{
			{
				Text: "You are a world-class Technical Writer and Software Architect. " +
					"Your task is to analyze the provided README.md content and extract core project concepts into a structured JSON format. " +
					"Focus on identifying the engineering challenges, architectural decisions, and the technical solution. " +
					"If you find Mermaid.js diagrams or complex architectural ASCII art, extract them into the ArchDiagram field. " +
					"The output MUST be valid JSON matching the requested schema.",
			},
		},
	}

	// Configure the generation request for structured JSON output
	config := &genai.GenerateContentConfig{
		SystemInstruction: systemInstruction,
		ResponseMIMEType:  "application/json",
		ResponseSchema: &genai.Schema{
			Type: genai.TypeObject,
			Properties: map[string]*genai.Schema{
				"Title":        {Type: genai.TypeString, Description: "The main title of the project"},
				"Subtitle":     {Type: genai.TypeString, Description: "A punchy, one-sentence subtitle describing the project"},
				"Description":  {Type: genai.TypeString, Description: "A detailed overview of what the project does and why it matters"},
				"Challenge":    {Type: genai.TypeString, Description: "The specific technical problem or hurdle that needed to be overcome"},
				"Solution":     {Type: genai.TypeString, Description: "The technical approach and implementation used to solve the challenge"},
				"Architecture": {Type: genai.TypeString, Description: "A high-level description of the system's architecture and design patterns"},
				"ArchDiagram":  {Type: genai.TypeString, Description: "Mermaid.js code blocks or ASCII art representing the architecture. Include the mermaid code block markers if applicable."},
				"TechStack": {
					Type:        genai.TypeArray,
					Items:       &genai.Schema{Type: genai.TypeString},
					Description: "A list of core technologies, frameworks, and languages used",
				},
				"KeyFeatures": {
					Type:        genai.TypeArray,
					Items:       &genai.Schema{Type: genai.TypeString},
					Description: "A list of the most important technical features or highlights",
				},
				"GitHubURL": {Type: genai.TypeString, Description: "The URL to the GitHub repository if found"},
			},
			Required: []string{"Title", "Subtitle", "Challenge", "Solution", "Architecture", "TechStack"},
		},
	}

	// Prepare the prompt
	prompt := fmt.Sprintf("Extract project details from the following README content:\n\n%s", readme)

	// Call Gemini
	resp, err := client.Models.GenerateContent(ctx, model, genai.Text(prompt), config)
	if err != nil {
		return nil, fmt.Errorf("gemini generation failed: %w", err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no content generated by AI")
	}

	// Extract the JSON text from the response
	responseText := resp.Candidates[0].Content.Parts[0].Text

	// Unmarshal into a temporary Product struct
	var product models.Product
	if err := json.Unmarshal([]byte(responseText), &product); err != nil {
		return nil, fmt.Errorf("failed to unmarshal AI response: %w. Response text: %s", err, responseText)
	}

	return &product, nil
}
